### ISSUE TITLE
Dynamic config loading

### ISSUE THREAD

**Issue by vfarcic** [abhikmitra/ng-joyride#2]
Is there a way to load config data dynamically? I want to send JSON from the server and refresh it depending on the screen user is located on.

**Comment by lakshmankotipalli** [comment]
Hi Abhik, I am using ngjoyride, inside $scope.config, for a particular selector, I gave type: "element", and placement: "right", but not able to find the popup. Instead of popup, I am able to see the particular element highlighted by white background.
The code will look like
			{
				type: "title",
				selector: "#heading",
				text: "Hi this is heading",
				placement: "right",
				scroll: true
			}
And, I am calling joyride like this : 
<div id="heading" ng-joy-ride="startJoyRide" config="config" on-finish="onFinish()" on-skip="onFinish()">
But when I gave type: "title", I am able to see alert kind of box like the first pop-up in your demo (http://abhikmitra.github.io/ng-joyride-demo/#/) . 
Is there a problem with my initialization? or what is going wrong!!?

**Comment by abhikmitra** [comment]
do you have plunkr that I can look at ?

**Comment by lakshmankotipalli** [comment]
Plunker I was not able to add. But the code I mentioned above is the only thing which gives me issues!

**Comment by lakshmankotipalli** [comment]
@abhikmitra  I am using Ionic framework, so is this the reason I was not able to see the bootstrap popovers whenever i use 'element' ? pls help
